language: node_js
node_js:
  - '14'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn run prod:scss
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: eu-central-1
  local_dir: '/'
  on:
    branch: master